<a href="https://colab.research.google.com/github/khatana706/DATA-SCIENCE/blob/main/email_spam_or_not_using_naive_bayes__ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [4]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [7]:
len(x_train)

4457

In [8]:
len(x_test)

1115

In [9]:
x_train.values

array(["I'm working technical support :)voice process.networking field.",
       'Shop till u Drop, IS IT YOU, either 10K, 5K, £500 Cash or £100 Travel voucher, Call now, 09064011000. NTT PO Box CR01327BT fixedline Cost 150ppm mobile vary',
       'Ya that one is slow as poo', ...,
       "Sorry, I'll call later in meeting.",
       'Customer place i will call you.',
       'Good afternoon sunshine! How dawns that day ? Are we refreshed and happy to be alive? Do we breathe in the air and smile ? I think of you, my love ... As always'],
      dtype=object)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)
x_train_count. toarray()[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [12]:
model.fit(x_train_count, y_train)

MultinomialNB()

In [14]:
emails = [
          'Hey mohan, we can get together to watch football game tomorrow?',
          'Upto 20% discount on parking,exclusive offer just for you, Dont miss this reward! '
]
emails_counts = cv.transform(emails)
model.predict(emails_counts)

array([0, 1])

In [16]:
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9829596412556054

In [30]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
                 ('vectorizer', CountVectorizer()),
                 ('nb', MultinomialNB())
])

In [31]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
clf.score(x_test, y_test)

0.9829596412556054

In [33]:
clf.predict(emails)

array([0, 1])