<a href="https://colab.research.google.com/github/khatana706/DATA-SCIENCE/blob/main/homeprice_using_linear_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('/content/homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median()

4.0

In [5]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
from sklearn import linear_model

In [9]:
reg = linear_model.LinearRegression()

In [10]:
reg.fit(df[['area' , 'bedrooms' , 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
reg.intercept_

221323.00186540396

In [13]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [14]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.00186540396

498408.251574024

In [15]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [16]:
import pickle

In [17]:
with open('reg_pickle', 'wb') as f:
  pickle.dump(reg,f)

In [18]:
with open('reg_pickle', 'rb') as f:
  ns = pickle.load(f)

In [19]:
ns.predict([[2500,4,5]])

array([578876.03748933])

In [20]:
!pip install --upgrade scikit-learn==0.20.3

In [21]:
import joblib
from sklearn.externals import joblib

In [24]:
joblib.dump(reg, 'reg_joblib')

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py:104: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  pickler.file_handle.write(chunk.tostring('C'))
/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py:104: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  pickler.file_handle.write(chunk.tostring('C'))


['reg_joblib']

In [25]:
ns = joblib.load('reg_joblib')

In [29]:
ns.predict([[2500,4,5]])

array([578876.03748933])

In [30]:
ns.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [31]:
ns.intercept_

221323.00186540396